language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23

    # The SDK version used to compile your project
    - android-23

before_install:
- export LANG=pt_BR.UTF-8
- npm install -g npm
- npm install -g cordova ionic

script:
- npm install
- ionic platform add android
- ionic build android
env:
  global:
  - APP_NAME="Diferentonas"
  - DEVELOPER_NAME="Luiz Augusto de Macêdo Morais"
  - PROFILE_NAME="Luiz Augusto Morais"
  - HOCKEYAPP_UPLOAD_BRANCH="master"
